# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20150324_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=models.TextField(verbose_name='body'),
        ),
    ]
